// Mocks generated by Mockito 5.4.4 from annotations
// in personal_expense_tracker/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_expense_tracker/src/features/expenses/domain/entities/expense.dart'
    as _i4;
import 'package:personal_expense_tracker/src/features/expenses/domain/repositories/expense_repository.dart'
    as _i2;
import 'package:personal_expense_tracker/src/features/expenses/domain/usecases/add_expense.dart'
    as _i6;
import 'package:personal_expense_tracker/src/features/expenses/domain/usecases/delete_expense.dart'
    as _i7;
import 'package:personal_expense_tracker/src/features/expenses/domain/usecases/get_expenses.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpenseRepository_0 extends _i1.SmartFake
    implements _i2.ExpenseRepository {
  _FakeExpenseRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i2.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Expense>> getExpenses() => (super.noSuchMethod(
        Invocation.method(
          #getExpenses,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Expense>>.value(<_i4.Expense>[]),
      ) as _i3.Future<List<_i4.Expense>>);

  @override
  _i3.Future<void> addExpense(_i4.Expense? expense) => (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [expense],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExpense(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetExpenses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExpenses extends _i1.Mock implements _i5.GetExpenses {
  MockGetExpenses() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExpenseRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ExpenseRepository);

  @override
  _i3.Future<List<_i4.Expense>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Expense>>.value(<_i4.Expense>[]),
      ) as _i3.Future<List<_i4.Expense>>);
}

/// A class which mocks [AddExpense].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddExpense extends _i1.Mock implements _i6.AddExpense {
  MockAddExpense() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExpenseRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ExpenseRepository);

  @override
  _i3.Future<void> call(_i4.Expense? expense) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [expense],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DeleteExpense].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteExpense extends _i1.Mock implements _i7.DeleteExpense {
  MockDeleteExpense() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExpenseRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ExpenseRepository);

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
